INSERT INTO `neadept_table` (`id`, `name`) VALUES
	(19, 'Corporate Planning Office (CPO)'),
	(18, 'Information Technology & Communication Services Department (ITCSD)'),
	(17, 'NEA-EC Training Institute (NETI)'),
	(16, 'Rural Electrification Special Program Office (RESPO)'),
	(15, 'Corporate Communication & Social Marketing Office (CCSMO)'),
	(14, 'Office for Performance Assessment and Special Studies (OPASS)'),
	(13, 'Office of the Administrator'),
	(12, 'Accounts Management & Guarantee Department (AMGD)'),
	(11, 'Institutional Development Department (IDD)'),
	(10, 'Management and Consultancy Services Office (MCSO)'),
	(9, 'Total Electrification and Renewable Energy Development Department'),
	(8, 'Disaster Risk Reduction and Management Department'),
	(7, 'Engineering Department'),
	(6, 'Internal Audit and Quality Management Office'),
	(5, 'Electric Cooperative Audit Department'),
	(4, 'Human Resources & Administration Department (HRAD)'),
	(3, 'Finance Services Department (FSD)'),
	(2, 'Regulatory Affairs Office (RAO)'),
	(1, 'Legal Servies Office (LSO)');
